### ISSUE TITLE
Shape shadows are always applied

### ISSUE THREAD

**Issue by ivanignatiev** [David-Summers/Azure-Design#19]
Hello, 

I have an issue with shape shadows. 

When I modify the shape with the setting **Effects** -> **None**

![image](https://user-images.githubusercontent.com/1072103/87803521-dedb2a00-c852-11ea-8928-05bfa75025cc.png)

I try to reuse my modified shape in the current document where I had shapes from Azure-Full-Colour stensil with shadows, but for the modified shape: the shadow effect is always applied

![image](https://user-images.githubusercontent.com/1072103/87803732-337ea500-c853-11ea-85a8-ffbf9bc2d6bc.png)

There is no issues if I am using my modified shape in the new Visio document.

Does anybody have the same issue ? 

Thank you for any help!

**Comment by David-Summers** [comment]
Hi this will be due to a setting on the master shape. If you want to define your own style then edit the master shape properties 

![image](https://user-images.githubusercontent.com/53208734/87843249-4e562580-c8f6-11ea-859d-e2018ccdd963.png)

and uncheck "Match master by name on drop"

![image](https://user-images.githubusercontent.com/53208734/87843257-62018c00-c8f6-11ea-9ed5-add18e523014.png)

**Comment by ivanignatiev** [comment]
Thank you but unfortunately I had "Match master by name on drop" unchecked :(

![image](https://user-images.githubusercontent.com/1072103/87849603-311b5a00-c8ea-11ea-890a-a1b8f54f4c62.png)

**Comment by ivanignatiev** [comment]
I found the solution, if somebody has the same issue: 

- Go to Developer -> Drawing Explorer
- Select Masters and remove previous Master shapes with Shadows

Unfortunately, I do not know why just unchecking "Match master by name on drop" did not worked for me.
